@echo off
rem DRY RUN twin of launch-rd.cmd, task Natively-flight-rd-dry: the same preconditions, environment block, commit check, committed-text shas, wav:check, router dist proofs and behavioural guard, then it stops. No flight, no app, no audio, no API call.
rem Generated by gen-launchers-rd.mjs from launch-rd-src.txt. The flight launcher and this one are composed from the same common section, so they cannot drift apart. Never edit this file by hand and never with sed.
rem Its GUARD OK line and its NIGHT GATES OK line are required before the real task is registered. The precheck task starts this task itself and reads its log.
rem Same placeholder rule as the flight launcher: node gen-launchers-rd.mjs with --commit, --t, --deadline-min and --ctx-sha12.
rem Exit codes are the flight launcher's steps before the flight: 9, 8, 7, 6, 12, 14, 5, 3, 4, and 0 when every check passed. This guard line does not pass --require-precheck: no precheck exists yet when the dry twin runs.
rem NOTE ON STYLE: no parentheses inside any echo in an if-block, see launch-rd.cmd.
if not exist "electron\test\golden\interview60.flight.mjs" (
  echo wrong working directory: %CD% >> "%TEMP%\natively-rd-launcher-error.log"
  exit /b 9
)
if not exist "electron\test\golden\live40.wav" (
  echo live40.wav missing - build the audio first >> "%TEMP%\natively-rd-launcher-error.log"
  exit /b 8
)
if not exist "electron\test\golden\live40.questions.mjs" (
  echo live40 roster missing from this checkout >> "%TEMP%\natively-rd-launcher-error.log"
  exit /b 7
)
rem Guard: the harness must stop the app when a run ends - 5952b23.
findstr /C:"process.on('exit', appStop)" "electron\test\golden\interview60.run.mjs" >nul 2>&1
if not "%errorlevel%"=="0" (
  echo the harness does not stop the app when a run ends - pick 5952b23 into this checkout >> "%TEMP%\natively-rd-launcher-error.log"
  exit /b 6
)
rem The environment: every variable that changes a model, a level, the hedge, the earlier-question block or the follow-up parent is cleared. A set with no value UNSETS the name in cmd. NATIVELY_VERBAL_HEDGE is cleared too: the hedge is ON by default and the guard refuses any value of it. The names set to a value are this hour's own: the router flag, the roster, the arms, the focused arms off, the task time, the probe deadline and the smoke's context sha.
set NATIVELY_STT_PROVIDER=deepgram
set NATIVELY_LIVE_ROUTER=1
set NATIVELY_ROSTER=live40
set NATIVELY_SCENARIOS=
set NATIVELY_EARLIER_QUESTION=
set NATIVELY_FLIGHT_ARMS=high,low,captured-high
set NATIVELY_FLIGHT_FOCUSED=off
set NATIVELY_ROUTER_CONTEXT_SHA12=b2a43a2159a2
set I60_PROBE_DEADLINE_MIN=35
set NATIVELY_RD_EXTRA_REQUESTS=0
set NATIVELY_RD_T=2026-10-07 03:00
set NATIVELY_GEMINI_THINKING_LEVEL=
set NATIVELY_VERBAL_PRIMARY_MODEL=
set NATIVELY_VERBAL_HEDGE=
set NATIVELY_VERBAL_HEDGE_TRIGGER_MS=
set NATIVELY_FOLLOWUP_PARENT=
set NATIVELY_LIVE_MODEL=
set NATIVELY_LIVE_MODE=
set NATIVELY_AUTOSTART_MEETING=
set NATIVELY_CAPTURE_PROMPTS=
set NATIVELY_QUESTION_DETECTION_MODEL=
set NATIVELY_FIRST_TOKEN_TIMEOUT_MS=
set NATIVELY_TURN_GATE_MS=
set NATIVELY_TURN_SETTLE_MS=
set NATIVELY_TURN_UNFINISHED_HOLD_MS=
set NATIVELY_TURN_CONTINUATION_MS=
set NATIVELY_TURN_MAX_HOLD_MS=
set NATIVELY_TURN_WORDLESS_GRACE_MS=
set NATIVELY_DETECTOR_CALIBRATE=
set NATIVELY_DETECTOR_CHAIN_TEST=
set NATIVELY_DETECTOR_CHAIN_TEST_QUESTIONS=
set NATIVELY_GEMMA_TTFT_MS=
set NATIVELY_GEMMA_MAX_ATTEMPTS=
set NATIVELY_GEMMA_VISION_TTFT_MS=
set NATIVELY_GEMMA_VISION_TTFT_BASE_MS=
set NATIVELY_GEMMA_VISION_TTFT_PER_IMAGE_MS=
set NATIVELY_GEMMA_VISION_MAX_ATTEMPTS=
set NATIVELY_API_URL=
set NATIVELY_BUILD_ALL_MAC_ARCHES=
set NATIVELY_FLIGHT_COMMIT=fade67f8a1d223a3faa59a2aea02e77c0f19e024
rem The commit check: 40 lowercase hex characters, nothing else. An unfilled placeholder, a short hash, a long one and an uppercase one all fail here, before anything runs. findstr cannot count to 40 in a pattern, so the length is tested by substring.
set COMMIT_OK=1
echo %NATIVELY_FLIGHT_COMMIT%| findstr /R /X "[0-9a-f][0-9a-f]*" >nul 2>&1
if errorlevel 1 set COMMIT_OK=0
if "%NATIVELY_FLIGHT_COMMIT:~39,1%"=="" set COMMIT_OK=0
if not "%NATIVELY_FLIGHT_COMMIT:~40,1%"=="" set COMMIT_OK=0
if "%COMMIT_OK%"=="0" (
  echo NATIVELY_FLIGHT_COMMIT is not a full 40 character hash - the placeholder was not filled in - run gen-launchers-rd.mjs with the commit >> "%TEMP%\natively-rd-launcher-error.log"
  exit /b 12
)
echo === LAUNCHER rd-dry start %DATE% %TIME% commit %NATIVELY_FLIGHT_COMMIT% T %NATIVELY_RD_T% === >> electron\test\golden\interview60.runs\flight-rd-dry.launcher.log
rem The committed texts, FIRST: the sha256 of each passes file as committed at HEAD, then the arming record's sha256 or ARMING absent. The dry run precedes the record, so absent is not an error here; the precheck gates on the record, and the result note quotes these lines.
"C:\Program Files\nodejs\node.exe" "%~dp0rd-sha-lines.mjs" --root "%CD%" --passes "PREREGISTER-router-default.md" --arming "%~dp0ARMING-flight-rd.md" >> electron\test\golden\interview60.runs\flight-rd-dry.launcher.log 2>&1
if not "%errorlevel%"=="0" (
  echo a committed text is missing at HEAD - see flight-rd-dry.launcher.log >> "%TEMP%\natively-rd-launcher-error.log"
  exit /b 14
)
rem Guard: the audio must hold exactly the roster's clips and gaps. NATIVELY_ROSTER=live40 was set above.
"C:\Program Files\nodejs\node.exe" electron\test\golden\interview60.run.mjs wav:check >> electron\test\golden\interview60.runs\flight-rd-dry.launcher.log 2>&1
if not "%errorlevel%"=="0" (
  echo live40.wav does not match the live40 roster - see flight-rd-dry.launcher.log >> "%TEMP%\natively-rd-launcher-error.log"
  exit /b 5
)
rem Router dist proofs 1: the cue build via dist-proof.mjs, the router markers, and the sha256 of the three router dist files, all printed into the log. The root is passed as the current folder in full: dist-proof.mjs fails on a relative root such as a single dot.
echo === DIST BEFORE THE RUN === >> electron\test\golden\interview60.runs\flight-rd-dry.launcher.log
"C:\Program Files\nodejs\node.exe" "%~dp0rd-proofs.mjs" --root "%CD%" >> electron\test\golden\interview60.runs\flight-rd-dry.launcher.log 2>&1
if not "%errorlevel%"=="0" (
  echo router dist proofs 1 failed - see flight-rd-dry.launcher.log >> "%TEMP%\natively-rd-launcher-error.log"
  exit /b 3
)
rem BEHAVIOURAL guard, the dry form: every check of the real launcher except the precheck stamp, which does not exist when the dry twin runs. Calibrated by breaking each premise once, see guard-rd-cal.txt.
"C:\Program Files\nodejs\node.exe" "%~dp0guard-rd.mjs" >> electron\test\golden\interview60.runs\flight-rd-dry.launcher.log 2>&1
set GUARD_EXIT=%errorlevel%
if "%GUARD_EXIT%"=="10" (
  echo === LAUNCHER rd-dry GUARD WINDOW ONLY exit 10 - only g4-clock failed - no error log written === >> electron\test\golden\interview60.runs\flight-rd-dry.launcher.log
  exit /b 10
)
if not "%GUARD_EXIT%"=="0" (
  echo behavioural guard failed - see flight-rd-dry.launcher.log >> "%TEMP%\natively-rd-launcher-error.log"
  exit /b 4
)
echo === LAUNCHER rd-dry done %DATE% %TIME% === >> electron\test\golden\interview60.runs\flight-rd-dry.launcher.log
exit /b 0
