@echo off
rem Router-default smoke, plan Task 17: the whole live40.wav hour with the router on, run label router-smoke. App hour only, no flight.mjs, so FLIGHT_FOCUSED is not set.
rem Generated by gen-launch-router-smoke.mjs, which reads the bytes back. Never edit this file by hand and never with sed.
rem No key wrapper: like launch-eq.cmd, the app reads its own credentials. No key is read or printed here.
rem Exit codes: 9 MAIN not found or wrong folder, 8 live40.wav missing, 6 harness does not stop the app, 5 wav:check failed, then the auto run own exit code.
rem NOTE ON STYLE: no parentheses inside any echo in an if-block.
rem MAIN sits under a non-ASCII folder name: found by wildcard so this file stays ASCII.
for /d %%D in ("%USERPROFILE%\OneDrive\Masa*") do if exist "%%D\natively-cluely-ai-assistant\.git" cd /d "%%D\natively-cluely-ai-assistant"
if not exist "electron\test\golden\interview60.run.mjs" (
  echo wrong working directory: %CD% >> "%TEMP%\natively-router-smoke-launcher-error.log"
  exit /b 9
)
if not exist "electron\test\golden\live40.wav" (
  echo live40.wav missing - build the audio first >> "%TEMP%\natively-router-smoke-launcher-error.log"
  exit /b 8
)
findstr /C:"process.on('exit', appStop)" "electron\test\golden\interview60.run.mjs" >nul 2>&1
if not "%errorlevel%"=="0" (
  echo the harness does not stop the app when a run ends >> "%TEMP%\natively-router-smoke-launcher-error.log"
  exit /b 6
)
set NATIVELY_LIVE_ROUTER=1
set NATIVELY_ROSTER=live40
set NATIVELY_STT_PROVIDER=deepgram
set NATIVELY_GEMINI_THINKING_LEVEL=
set NATIVELY_VERBAL_PRIMARY_MODEL=
set NATIVELY_VERBAL_HEDGE=
set NATIVELY_VERBAL_HEDGE_TRIGGER_MS=
set NATIVELY_FOLLOWUP_PARENT=
set NATIVELY_LIVE_MODEL=
set NATIVELY_LIVE_MODE=
set NATIVELY_AUTOSTART_MEETING=
set NATIVELY_CAPTURE_PROMPTS=
set NATIVELY_QUESTION_DETECTION_MODEL=
set NATIVELY_FIRST_TOKEN_TIMEOUT_MS=
set NATIVELY_TURN_GATE_MS=
set NATIVELY_TURN_SETTLE_MS=
set NATIVELY_TURN_UNFINISHED_HOLD_MS=
set NATIVELY_TURN_CONTINUATION_MS=
set NATIVELY_TURN_MAX_HOLD_MS=
set NATIVELY_TURN_WORDLESS_GRACE_MS=
set NATIVELY_DETECTOR_CALIBRATE=
set NATIVELY_DETECTOR_CHAIN_TEST=
set NATIVELY_DETECTOR_CHAIN_TEST_QUESTIONS=
set NATIVELY_GEMMA_TTFT_MS=
set NATIVELY_GEMMA_MAX_ATTEMPTS=
set NATIVELY_GEMMA_VISION_TTFT_MS=
set NATIVELY_GEMMA_VISION_TTFT_BASE_MS=
set NATIVELY_GEMMA_VISION_TTFT_PER_IMAGE_MS=
set NATIVELY_GEMMA_VISION_MAX_ATTEMPTS=
set NATIVELY_API_URL=
set NATIVELY_BUILD_ALL_MAC_ARCHES=
set I60_PROBE_DEADLINE_MIN=
set NATIVELY_EARLIER_QUESTION=
set NATIVELY_FLIGHT_ARMS=
set NATIVELY_SCENARIOS=
echo === LAUNCHER router-smoke start %DATE% %TIME% === >> electron\test\golden\interview60.runs\router-smoke.launcher.log
"C:\Program Files\nodejs\node.exe" electron\test\golden\interview60.run.mjs wav:check >> electron\test\golden\interview60.runs\router-smoke.launcher.log 2>&1
if not "%errorlevel%"=="0" (
  echo live40.wav does not match the live40 roster - see router-smoke.launcher.log >> "%TEMP%\natively-router-smoke-launcher-error.log"
  exit /b 5
)
"C:\Program Files\nodejs\node.exe" electron\test\golden\interview60.run.mjs auto router-smoke >> electron\test\golden\interview60.runs\router-smoke.launcher.log 2>&1
set SMOKE_EXIT=%errorlevel%
echo === SMOKE EXIT %SMOKE_EXIT% %DATE% %TIME% === >> electron\test\golden\interview60.runs\router-smoke.launcher.log
"C:\Program Files\nodejs\node.exe" electron\test\golden\interview60.run.mjs app:stop >> electron\test\golden\interview60.runs\router-smoke.launcher.log 2>&1
echo === LAUNCHER router-smoke done %DATE% %TIME% === >> electron\test\golden\interview60.runs\router-smoke.launcher.log
exit /b %SMOKE_EXIT%
