@echo off
rem Merge the h40d Opus verdicts into MAIN's run dir. Run with cwd = MAIN, AFTER the flight task ended.
rem   h40d-merge.cmd grader-model-id run-dir     the exact grader model id read from the grading agents' transcripts, then the run dir relative to MAIN
rem Generated by gen-launchers.mjs from h40d-merge-src.txt: h40c-merge.cmd re-pointed. Verdicts are read from the validation-hour folder, files h40d-verdicts-TAG.json. Three arms are added, the no-cue twins.
rem The in-app verdicts file is required. Every other arm is optional: a missing verdicts file prints SKIPPED-MISSING with its tag and merges nothing, never another file.
rem Every merge passes --model: judge.mjs refuses a merge without the exact id.
rem GOTCHA: the bare 3.1 default arm reads the PLAIN interview60.answers.json.
rem NOTE: no parentheses in any echo inside an if-block. See the s50k launcher defect.
setlocal
if "%~2"=="" echo USAGE: h40d-merge.cmd grader-model-id run-dir
if "%~2"=="" exit /b 12
set M=%~1
set R=%~2
set S=C:\Users\sotka\AppData\Local\Temp\claude\C-407A~1\9C5886~1\SCRATC~1\VALIDA~1\INSTRU~1\LAUNCH~1\cal\d03\verd
set N="C:\Program Files\nodejs\node.exe"
set J=electron\test\golden\interview60.judge.mjs

if not exist "%R%\interview60.flight.done.json" echo WRONG CWD OR RUN DIR: run this from MAIN with the h40d run dir
if not exist "%R%\interview60.flight.done.json" exit /b 13
rem Not in h40c: an absolute run dir passed from the wrong folder passes the check above and would receive a verdicts file before the judge script failed to start.
if not exist "%J%" echo WRONG CWD: the judge script is not here, run this from MAIN
if not exist "%J%" exit /b 13

if not exist "%S%\h40d-verdicts-inapp.json" echo MISSING h40d-verdicts-inapp.json
if not exist "%S%\h40d-verdicts-inapp.json" exit /b 10
copy /y "%S%\h40d-verdicts-inapp.json" "%R%\interview60.judge.verdicts.json" >nul
%N% %J% %R% --verdicts %R%\interview60.judge.verdicts.json --model %M%
if errorlevel 1 exit /b 1

call :arm captured-low               gemini-3.1-flash-lite_captured-low
call :arm captured-low-r2            gemini-3.1-flash-lite_captured-low-r2
call :arm captured-low-r3            gemini-3.1-flash-lite_captured-low-r3
call :arm captured-minimal           gemini-3.1-flash-lite_captured-minimal
call :arm low                        gemini-3.1-flash-lite_low
call :arm captured-high              gemini-3.5-flash-lite_captured-high
call :arm captured-high-r2           gemini-3.5-flash-lite_captured-high-r2
call :arm captured-high-r3           gemini-3.5-flash-lite_captured-high-r3
call :arm captured-no-cues-high      gemini-3.5-flash-lite_captured-no-cues-high
call :arm captured-no-cues-high-r2   gemini-3.5-flash-lite_captured-no-cues-high-r2
call :arm captured-no-cues-high-r3   gemini-3.5-flash-lite_captured-no-cues-high-r3
call :arm high                       gemini-3.5-flash-lite_high
call :arm bare35                     gemini-3.5-flash-lite

rem The bare 3.1 default arm: plain answers file, suffixed judge output. Optional like the others.
if not exist "%S%\h40d-verdicts-bare31.json" echo SKIPPED-MISSING bare31
if not exist "%S%\h40d-verdicts-bare31.json" goto done
copy /y "%S%\h40d-verdicts-bare31.json" "%R%\interview60.judge.verdicts.gemini-3.1-flash-lite.json" >nul
%N% %J% %R% --answers %R%\interview60.answers.json --verdicts %R%\interview60.judge.verdicts.gemini-3.1-flash-lite.json --model %M%
if errorlevel 1 echo MERGE-FAILED bare31

:done
echo ALL MERGES RAN
exit /b 0

:arm
if not exist "%S%\h40d-verdicts-%1.json" echo SKIPPED-MISSING %1
if not exist "%S%\h40d-verdicts-%1.json" exit /b 0
copy /y "%S%\h40d-verdicts-%1.json" "%R%\interview60.judge.verdicts.%2.json" >nul
%N% %J% %R% --answers %R%\interview60.answers.%2.json --verdicts %R%\interview60.judge.verdicts.%2.json --model %M%
if errorlevel 1 echo MERGE-FAILED %1
exit /b 0
