@echo off
rem Bundle-1 final flight, task Natively-flight-b1 (UNREGISTERED until the user picks a time, register-b1.ps1 -Which flight): live40, router ON, NO fault drill, arms high,low,captured-high as r1 flew, run label b1-final.
rem Generated by gen-launchers-b1.mjs, which reads the bytes back. Never edit this file by hand and never with sed: change the generator and re-run it.
rem Derived from router-default launch-rd.cmd and launch-router-smoke.cmd: same guard chain, same exit codes. No key wrapper: the app reads its own credentials; no key is read or printed here.
rem T arrives as the FIRST ARGUMENT from the task action, as yyyy-MM-dd HH:mm local +03:00: the guard checks the clock against it, the night gates read it.
rem Exit codes: 9 wrong folder, 8 audio missing, 7 roster missing, 6 harness does not stop the app, 12 commit not a full hash, 13 T argument missing, 11 a b1 tool missing, 5 wav:check failed, 3 dist proofs failed before or after the run, 4 guard failed, then the run own exit code, then the smoke read verdict.
rem NOTE ON STYLE: no parentheses inside any echo in an if-block. On 2026-09-20 a guard message citing a commit in parentheses closed its own if-block early and a flight died before takeoff with no log.
rem MAIN sits under a non-ASCII folder name: found by wildcard so this file stays ASCII. The error log must not exist at arming.
for /d %%D in ("%USERPROFILE%\OneDrive\Masa*") do if exist "%%D\natively-cluely-ai-assistant\.git" cd /d "%%D\natively-cluely-ai-assistant"
if not exist "electron\test\golden\interview60.flight.mjs" (
  echo wrong working directory: %CD% >> "%TEMP%\natively-b1-flight-launcher-error.log"
  exit /b 9
)
if not exist "electron\test\golden\live40.wav" (
  echo live40.wav missing - build the audio first >> "%TEMP%\natively-b1-flight-launcher-error.log"
  exit /b 8
)
if not exist "electron\test\golden\live40.questions.mjs" (
  echo live40 roster missing from this checkout >> "%TEMP%\natively-b1-flight-launcher-error.log"
  exit /b 7
)
rem Guard: the harness must stop the app when a run ends - 5952b23.
findstr /C:"process.on('exit', appStop)" "electron\test\golden\interview60.run.mjs" >nul 2>&1
if not "%errorlevel%"=="0" (
  echo the harness does not stop the app when a run ends - pick 5952b23 into this checkout >> "%TEMP%\natively-b1-flight-launcher-error.log"
  exit /b 6
)
if not exist "%~dp0..\smoke\guard-b1.mjs" (
  echo a b1 tool is missing: guard-b1.mjs >> "%TEMP%\natively-b1-flight-launcher-error.log"
  exit /b 11
)
if not exist "%~dp0..\smoke\b1-proofs.mjs" (
  echo a b1 tool is missing: b1-proofs.mjs >> "%TEMP%\natively-b1-flight-launcher-error.log"
  exit /b 11
)
if not exist "%~dp0..\smoke\observe-session.ps1" (
  echo a b1 tool is missing: observe-session.ps1 >> "%TEMP%\natively-b1-flight-launcher-error.log"
  exit /b 11
)
rem T: the first argument. An empty one refuses before anything runs.
set NATIVELY_B1_T=%~1
if "%NATIVELY_B1_T%"=="" (
  echo no T argument - the task passes T as yyyy-MM-dd HH:mm >> "%TEMP%\natively-b1-flight-launcher-error.log"
  exit /b 13
)
rem The environment. A set with no value UNSETS the name in cmd. Cleared: every model, level, hedge, earlier-question, follow-up, turn, Gemma and test-chain override. Set: this run own names.
set NATIVELY_STT_PROVIDER=deepgram
set NATIVELY_LIVE_ROUTER=1
set NATIVELY_ROSTER=live40
set NATIVELY_B1_KIND=flight
set NATIVELY_B1_TASK=Natively-flight-b1
set NATIVELY_B1_EXTRA_REQUESTS=150
set I60_PROBE_DEADLINE_MIN=35
rem The final flight runs NO drill (spec 7.1): the variable is unset here and the guard refuses any value of it. The arms, the focused arms and the router context sha are r1 own (the guard and the harness preflight check them).
set NATIVELY_FAULT_DRILL=
set NATIVELY_AUTOSTART_MEETING=
set NATIVELY_FLIGHT_ARMS=high,low,captured-high
set NATIVELY_FLIGHT_FOCUSED=off
set NATIVELY_ROUTER_CONTEXT_SHA12=b2a43a2159a2
set NATIVELY_GEMINI_THINKING_LEVEL=
set NATIVELY_VERBAL_PRIMARY_MODEL=
set NATIVELY_VERBAL_HEDGE=
set NATIVELY_VERBAL_HEDGE_TRIGGER_MS=
set NATIVELY_FOLLOWUP_PARENT=
set NATIVELY_LIVE_MODEL=
set NATIVELY_LIVE_MODE=
set NATIVELY_CAPTURE_PROMPTS=
set NATIVELY_QUESTION_DETECTION_MODEL=
set NATIVELY_FIRST_TOKEN_TIMEOUT_MS=
set NATIVELY_TURN_GATE_MS=
set NATIVELY_TURN_SETTLE_MS=
set NATIVELY_TURN_UNFINISHED_HOLD_MS=
set NATIVELY_TURN_CONTINUATION_MS=
set NATIVELY_TURN_MAX_HOLD_MS=
set NATIVELY_TURN_WORDLESS_GRACE_MS=
set NATIVELY_DETECTOR_CALIBRATE=
set NATIVELY_DETECTOR_CHAIN_TEST=
set NATIVELY_DETECTOR_CHAIN_TEST_QUESTIONS=
set NATIVELY_GEMMA_TTFT_MS=
set NATIVELY_GEMMA_MAX_ATTEMPTS=
set NATIVELY_GEMMA_VISION_TTFT_MS=
set NATIVELY_GEMMA_VISION_TTFT_BASE_MS=
set NATIVELY_GEMMA_VISION_TTFT_PER_IMAGE_MS=
set NATIVELY_GEMMA_VISION_MAX_ATTEMPTS=
set NATIVELY_API_URL=
set NATIVELY_BUILD_ALL_MAC_ARCHES=
set NATIVELY_EARLIER_QUESTION=
set NATIVELY_SCENARIOS=
set NATIVELY_FLIGHT_COMMIT=9d5bd9ea411dd4069f5367e7b4447ea263ec9aa1
rem The commit check: 40 lowercase hex characters, nothing else; the length is tested by substring because findstr cannot count to 40.
set COMMIT_OK=1
echo %NATIVELY_FLIGHT_COMMIT%| findstr /R /X "[0-9a-f][0-9a-f]*" >nul 2>&1
if errorlevel 1 set COMMIT_OK=0
if "%NATIVELY_FLIGHT_COMMIT:~39,1%"=="" set COMMIT_OK=0
if not "%NATIVELY_FLIGHT_COMMIT:~40,1%"=="" set COMMIT_OK=0
if "%COMMIT_OK%"=="0" (
  echo NATIVELY_FLIGHT_COMMIT is not a full 40 character hash - run gen-launchers-b1.mjs with the commit >> "%TEMP%\natively-b1-flight-launcher-error.log"
  exit /b 12
)
echo === LAUNCHER b1-flight start %DATE% %TIME% commit %NATIVELY_FLIGHT_COMMIT% T %NATIVELY_B1_T% === >> electron\test\golden\interview60.runs\b1-flight.launcher.log
certutil -hashfile "%~f0" SHA256 >> electron\test\golden\interview60.runs\b1-flight.launcher.log 2>&1
rem Guard: the audio must hold exactly the roster clips and gaps. NATIVELY_ROSTER=live40 was set above.
"C:\Program Files\nodejs\node.exe" electron\test\golden\interview60.run.mjs wav:check >> electron\test\golden\interview60.runs\b1-flight.launcher.log 2>&1
if not "%errorlevel%"=="0" (
  echo live40.wav does not match the live40 roster - see b1-flight.launcher.log >> "%TEMP%\natively-b1-flight-launcher-error.log"
  exit /b 5
)
rem Dist proofs 1: the reduced bundle markers and shas, and the sha256 of the proof files, printed into the log. The root is passed in full: a relative root fails.
echo === DIST BEFORE THE RUN === >> electron\test\golden\interview60.runs\b1-flight.launcher.log
"C:\Program Files\nodejs\node.exe" "%~dp0..\smoke\b1-proofs.mjs" --root "%CD%" >> electron\test\golden\interview60.runs\b1-flight.launcher.log 2>&1
if not "%errorlevel%"=="0" (
  echo dist proofs 1 failed - see b1-flight.launcher.log >> "%TEMP%\natively-b1-flight-launcher-error.log"
  exit /b 3
)
rem BEHAVIOURAL guard: with the precheck stamp and the clock window. Calibrated by breaking each premise once, see guard-b1-cal.txt.
"C:\Program Files\nodejs\node.exe" "%~dp0..\smoke\guard-b1.mjs" --kind flight --require-precheck >> electron\test\golden\interview60.runs\b1-flight.launcher.log 2>&1
if not "%errorlevel%"=="0" (
  echo behavioural guard failed - see b1-flight.launcher.log >> "%TEMP%\natively-b1-flight-launcher-error.log"
  exit /b 4
)
rem Observability: a read-only sampler records the console session, the electron session ids and the visible electron windows every 20 s. It stops on the stop file or after 120 min, and is stopped below.
del "electron\test\golden\interview60.runs\b1-flight.observe.stop" >nul 2>&1
start "" /b powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0..\smoke\observe-session.ps1" -Out "electron\test\golden\interview60.runs\b1-flight.observe.log" -Stop "electron\test\golden\interview60.runs\b1-flight.observe.stop" -EverySec 20 -MaxMin 120 >nul 2>&1
rem The flight itself. It stops the app by itself when it ends: process.on exit appStop, 5952b23.
"C:\Program Files\nodejs\node.exe" electron\test\golden\interview60.flight.mjs b1-final >> electron\test\golden\interview60.runs\b1-flight.launcher.log 2>&1
set RUN_EXIT=%errorlevel%
echo === RUN EXIT %RUN_EXIT% %DATE% %TIME% === >> electron\test\golden\interview60.runs\b1-flight.launcher.log
"C:\Program Files\nodejs\node.exe" electron\test\golden\interview60.run.mjs app:stop >> electron\test\golden\interview60.runs\b1-flight.launcher.log 2>&1
echo stop > "electron\test\golden\interview60.runs\b1-flight.observe.stop"
rem Dist proofs 2: the run rebuilds the dist when any electron source is newer than the oldest output, so THIS is the dist that ran. Each proof file sha256 must equal the one printed before the run, else the run is VOID.
echo === DIST AFTER THE RUN === >> electron\test\golden\interview60.runs\b1-flight.launcher.log
"C:\Program Files\nodejs\node.exe" "%~dp0..\smoke\b1-proofs.mjs" --root "%CD%" --same-as-log electron\test\golden\interview60.runs\b1-flight.launcher.log >> electron\test\golden\interview60.runs\b1-flight.launcher.log 2>&1
if not "%errorlevel%"=="0" (
  echo dist proofs 2 failed - the dist that ran is not the proven build - see b1-flight.launcher.log >> "%TEMP%\natively-b1-flight-launcher-error.log"
  exit /b 3
)
echo === LAUNCHER b1-flight done %DATE% %TIME% === >> electron\test\golden\interview60.runs\b1-flight.launcher.log
exit /b %RUN_EXIT%
