@echo off
rem Flight h40d, task Natively-flight-h40d: holdout40's fourth flight, cue mode's validation hour on MAIN after the cue merge.
rem Pre-registration PREREGISTER-h40d.r4.md, section 2 and section 7.4. ONE change under test against h40c: cue mode, always on in the build. Everything else is the shipped default: the verbal hedge is ON because its variable is cleared, no follow-up parent, no model or thinking override, Deepgram plus the Live ear, roster holdout40.
rem Generated by gen-launchers.mjs from launch-h40d-src.txt. Never edit this file by hand and never with sed: change the source text and re-run the generator, which reads the bytes back.
rem NATIVELY_FLIGHT_COMMIT below holds a PLACEHOLDER until the controller arms the launcher: node gen-launchers.mjs --commit followed by the registered HEAD hash. The commit check below refuses anything that is not a full 40 character lowercase hash.
rem Knowledge mode ON is a persisted setting, not an environment variable: guard-h40d.mjs reads it from the settings file.
rem Error log: natively-h40d-launcher-error.log in the TEMP folder must not exist at arming. Launcher log: interview60.runs, flight-h40d.launcher.log, in MAIN.
rem Exit codes: 9 wrong folder, 8 audio missing, 7 roster missing, 6 harness does not stop the app, 12 commit not a full hash, 5 wav:check failed, 3 dist proof failed before or after the run, 4 guard failed. After all of those the exit code is the flight's own.
rem NOTE ON STYLE: no parentheses inside any echo in an if-block. On 2026-09-20 a guard message citing a commit in parentheses closed its own if-block early, so the exit after it ran unconditionally and a flight died before takeoff with no log of any kind.
if not exist "electron\test\golden\interview60.flight.mjs" (
  echo wrong working directory: %CD% >> "%TEMP%\natively-h40d-launcher-error.log"
  exit /b 9
)
if not exist "electron\test\golden\holdout40.wav" (
  echo holdout40.wav missing - build the audio first >> "%TEMP%\natively-h40d-launcher-error.log"
  exit /b 8
)
if not exist "electron\test\golden\holdout40.questions.mjs" (
  echo holdout40 roster missing from this checkout - merge it first >> "%TEMP%\natively-h40d-launcher-error.log"
  exit /b 7
)
rem Guard: the harness must stop the app when a run ends - 5952b23.
findstr /C:"process.on('exit', appStop)" "electron\test\golden\interview60.run.mjs" >nul 2>&1
if errorlevel 1 (
  echo the harness does not stop the app when a run ends - pick 5952b23 into this checkout >> "%TEMP%\natively-h40d-launcher-error.log"
  exit /b 6
)
rem The environment of r4 section 2: every variable that changes a model, a level, the hedge or the follow-up parent is cleared. A set with no value UNSETS the name in cmd. NATIVELY_VERBAL_HEDGE is cleared too: the hedge is ON by default and the guard refuses any value of it.
set NATIVELY_STT_PROVIDER=deepgram
set NATIVELY_ROSTER=holdout40
set NATIVELY_SCENARIOS=
set NATIVELY_GEMINI_THINKING_LEVEL=
set NATIVELY_VERBAL_PRIMARY_MODEL=
set NATIVELY_VERBAL_HEDGE=
set NATIVELY_VERBAL_HEDGE_TRIGGER_MS=
set NATIVELY_FOLLOWUP_PARENT=
set NATIVELY_LIVE_MODEL=
set NATIVELY_LIVE_MODE=
set NATIVELY_AUTOSTART_MEETING=
set NATIVELY_CAPTURE_PROMPTS=
set NATIVELY_QUESTION_DETECTION_MODEL=
set NATIVELY_FIRST_TOKEN_TIMEOUT_MS=
set NATIVELY_TURN_GATE_MS=
set NATIVELY_TURN_SETTLE_MS=
set NATIVELY_TURN_UNFINISHED_HOLD_MS=
set NATIVELY_TURN_CONTINUATION_MS=
set NATIVELY_TURN_MAX_HOLD_MS=
set NATIVELY_TURN_WORDLESS_GRACE_MS=
set NATIVELY_DETECTOR_CALIBRATE=
set NATIVELY_DETECTOR_CHAIN_TEST=
set NATIVELY_DETECTOR_CHAIN_TEST_QUESTIONS=
set NATIVELY_GEMMA_TTFT_MS=
set NATIVELY_GEMMA_MAX_ATTEMPTS=
set NATIVELY_GEMMA_VISION_TTFT_MS=
set NATIVELY_GEMMA_VISION_TTFT_BASE_MS=
set NATIVELY_GEMMA_VISION_TTFT_PER_IMAGE_MS=
set NATIVELY_GEMMA_VISION_MAX_ATTEMPTS=
set NATIVELY_API_URL=
set NATIVELY_BUILD_ALL_MAC_ARCHES=
set I60_PROBE_DEADLINE_MIN=
set NATIVELY_FLIGHT_COMMIT=0123456789abcdef0123456789abcdef01234567
rem The commit check: 40 lowercase hex characters, nothing else. An unfilled placeholder, a short hash, a long one and an uppercase one all fail here, before anything runs. findstr cannot count to 40 in a pattern, so the length is tested by substring.
set COMMIT_OK=1
echo %NATIVELY_FLIGHT_COMMIT%| findstr /R /X "[0-9a-f][0-9a-f]*" >nul 2>&1
if errorlevel 1 set COMMIT_OK=0
if "%NATIVELY_FLIGHT_COMMIT:~39,1%"=="" set COMMIT_OK=0
if not "%NATIVELY_FLIGHT_COMMIT:~40,1%"=="" set COMMIT_OK=0
if "%COMMIT_OK%"=="0" (
  echo NATIVELY_FLIGHT_COMMIT is not a full 40 character hash - the placeholder was not filled in - run gen-launchers.mjs with the commit >> "%TEMP%\natively-h40d-launcher-error.log"
  exit /b 12
)
echo === LAUNCHER h40d start %DATE% %TIME% commit %NATIVELY_FLIGHT_COMMIT% === >> electron\test\golden\interview60.runs\flight-h40d.launcher.log
rem Guard: the audio must hold exactly the roster's clips and gaps.
"C:\Program Files\nodejs\node.exe" C:\Users\sotka\AppData\Local\Temp\claude\C-407A~1\9C5886~1\SCRATC~1\VALIDA~1\INSTRU~1\LAUNCH~1\cal\b10\stub\stub-run.mjs wav:check >> electron\test\golden\interview60.runs\flight-h40d.launcher.log 2>&1
if errorlevel 1 (
  echo holdout40.wav does not match the holdout40 roster - see flight-h40d.launcher.log >> "%TEMP%\natively-h40d-launcher-error.log"
  exit /b 5
)
rem Dist proof 1: the dist in MAIN is the combined cue build, every marker as expected. The root is passed as the current folder in full: dist-proof.mjs fails on a relative root such as a single dot.
echo === DIST BEFORE THE RUN === >> electron\test\golden\interview60.runs\flight-h40d.launcher.log
"C:\Program Files\nodejs\node.exe" "C:\Users\sotka\OneDrive\Masaüstü\natively-lab\sp\dist-proof.mjs" --root "%CD%" --expect combined --prefix-count 3 --offers-marker "offers block before the spoken answer" >> electron\test\golden\interview60.runs\flight-h40d.launcher.log 2>&1
if errorlevel 1 (
  echo dist proof 1 failed - the dist is not the combined build - see flight-h40d.launcher.log >> "%TEMP%\natively-h40d-launcher-error.log"
  exit /b 3
)
rem BEHAVIOURAL guard: roster, no model or thinking override, the built default and fallback and their levels, the R09 fix, the hedge resolving ON with its variable unset, trigger 5000 ms, follow-up parent off, dist not stale, the HEAD pin and the .env name scan, the cue build markers and knowledge mode ON. Calibrated by breaking each premise once, see guard-h40d-cal.txt.
"C:\Program Files\nodejs\node.exe" "%~dp0guard-h40d.mjs" >> electron\test\golden\interview60.runs\flight-h40d.launcher.log 2>&1
if errorlevel 1 (
  echo behavioural guard failed - see flight-h40d.launcher.log >> "%TEMP%\natively-h40d-launcher-error.log"
  exit /b 4
)
rem The flight itself. It stops the app by itself when it ends: process.on exit appStop, 5952b23.
"C:\Program Files\nodejs\node.exe" C:\Users\sotka\AppData\Local\Temp\claude\C-407A~1\9C5886~1\SCRATC~1\VALIDA~1\INSTRU~1\LAUNCH~1\cal\b10\stub\stub-flight.mjs h40d >> electron\test\golden\interview60.runs\flight-h40d.launcher.log 2>&1
set FLIGHT_EXIT=%errorlevel%
echo === FLIGHT EXIT %FLIGHT_EXIT% %DATE% %TIME% === >> electron\test\golden\interview60.runs\flight-h40d.launcher.log
rem Dist proof 2: the run rebuilds the dist when any electron source is newer than the oldest output, so THIS is the dist that flew.
echo === DIST AFTER THE RUN === >> electron\test\golden\interview60.runs\flight-h40d.launcher.log
"C:\Program Files\nodejs\node.exe" "C:\Users\sotka\OneDrive\Masaüstü\natively-lab\sp\dist-proof.mjs" --root "%CD%" --expect combined --prefix-count 3 --offers-marker "offers block before the spoken answer" >> electron\test\golden\interview60.runs\flight-h40d.launcher.log 2>&1
if errorlevel 1 (
  echo dist proof 2 failed - the dist that flew is not the combined build - see flight-h40d.launcher.log >> "%TEMP%\natively-h40d-launcher-error.log"
  exit /b 3
)
exit /b %FLIGHT_EXIT%
