// GENERATED by make-stamp-s50l.mjs from stamp.mjs (s50l file names only). Do not edit.
// Throwaway: pins the reference implementation and the recorded material by sha256, checks that
// every recorded arm B is exactly arm A + the block at the marker, and re-derives every parity
// fixture entry's block from its recorded inputs (the fixture must be reproducible by the
// reference before it can be asked of the app).
import fs from 'node:fs';
import { createHash } from 'node:crypto';
import { BLOCK_LABEL, insertBlock, gate, selectEarlier, formatBlock } from './earlierQuestions.ref.mjs';
const sha = (s) => createHash('sha256').update(s).digest('hex');
for (const f of ['earlierQuestions.ref.mjs', 'gate-report-s50l.mjs', 's50l-gated.json', 's50l-parity-fixture.json']) console.log(`${f}\t${sha(fs.readFileSync(f))}\t${fs.statSync(f).size} bytes`);
console.log(`label chars: ${BLOCK_LABEL.length}`);

const out = JSON.parse(fs.readFileSync('s50l-gated.json', 'utf8'));
let ok = true, totalAdded = 0;
for (const [id, o] of Object.entries(out)) {
    const rebuilt = insertBlock(o.userA, o.block);
    const same = rebuilt === o.userB;
    const added = o.userB.length - o.userA.length;
    totalAdded += added;
    const stripped = o.userB.replace(`${o.block}\n\n`, '');
    if (!same || stripped !== o.userA || added !== o.block.length + 2) ok = false;
    console.log(`${id}\t${o.kind}\t${o.cue}\tblock ${o.block.length}\tadded ${added}\tuserA ${o.userA.length}\tuserB ${o.userB.length}\tsha12 ${sha(o.block).slice(0, 12)}\t${same && stripped === o.userA ? 'OK' : 'MISMATCH'}`);
}
console.log(ok ? 'ARMS OK: every userB = userA + block + "\\n\\n" at the marker, nothing else' : 'ARMS MISMATCH');
console.log(`items: ${Object.keys(out).length}; mean added chars: ${(totalAdded / Object.keys(out).length).toFixed(0)}; max block: ${Math.max(...Object.values(out).map((o) => o.block.length))}`);

const fx = JSON.parse(fs.readFileSync('s50l-parity-fixture.json', 'utf8'));
let fxOk = true, withBlock = 0;
for (const [id, e] of Object.entries(fx)) {
    const g = gate(e.current);
    const block = g.fires ? formatBlock(selectEarlier(e.current, g.cue, e.answered, e.windowLines, e.now).lines) : '';
    if (block) withBlock++;
    if (block !== e.expectedBlock || g.cue !== e.expectedCue || sha(block).slice(0, 12) !== e.expectedSha) { fxOk = false; console.log(`PARITY FIXTURE MISMATCH ${id}`); }
}
console.log(fxOk ? `PARITY FIXTURE OK: ${Object.keys(fx).length} entries re-derived (${withBlock} with a block, ${Object.keys(fx).length - withBlock} empty)` : 'PARITY FIXTURE FAILED');
// Rule 8: the fixture check must fail on a broken input — corrupt the PARENT's text (the block is
// built from `answered`, not from `current`, so corrupting the current question proves nothing).
const src = fx[Object.keys(fx).find((k) => fx[k].expectedBlock)];
const broken = { ...src, answered: src.answered.map((a, i, arr) => (i === arr.length - 1 ? { ...a, text: `${a.text} REPLAY_BREAK` } : a)) };
const gb = gate(broken.current);
const bb = gb.fires ? formatBlock(selectEarlier(broken.current, gb.cue, broken.answered, broken.windowLines, broken.now).lines) : '';
console.log(bb === broken.expectedBlock ? 'FIXTURE CHECK CANNOT FAIL (bad)' : 'fixture check fails on a corrupted input: OK');
