import fs from 'node:fs';
const runDir = process.argv[2];
const tl = JSON.parse(fs.readFileSync(runDir + '/interview60.timeline.json', 'utf8'));
const dbg = fs.readFileSync(runDir + '/natively_debug.log', 'utf8');
const ts = (s) => Date.parse(s);
const since = tl.startedMs - 2000;
console.log('startedMs', tl.startedMs, new Date(tl.startedMs).toISOString());
console.log('since', since, new Date(since).toISOString());
const dispatchRe = /^(\S+) \[LOG\] \[Main\] dispatch: (answer|chip|drop|extend|hold|mark|supersede) source=(live|whisper) anchor="((?:[^"\\]|\\.)*)" verdict=(\w+)(?:[^\n]*? question="((?:[^"\\]|\\.)*)")?/gm;
const all = [...dbg.matchAll(dispatchRe)].map((m) => ({ at: ts(m[1]), action: m[2] }));
console.log('raw regex matches (unfiltered):', all.length);
const byAction = {};
for (const d of all) byAction[d.action] = (byAction[d.action]||0)+1;
console.log('by action (unfiltered):', byAction);
const filtered = all.filter((d) => d.at >= since);
console.log('filtered (at >= since):', filtered.length);
const byActionF = {};
for (const d of filtered) byActionF[d.action] = (byActionF[d.action]||0)+1;
console.log('by action (filtered):', byActionF);
const excluded = all.filter((d) => d.at < since);
console.log('excluded (at < since):', excluded.length, excluded.map(d=>d.action));
