const fs = require('fs');
const out = "C:/Users/sotka/OneDrive/Masaüstü/natively-lab/sp/calib-after8-31-A.json";
const g = (c,o,d,r) => ({correctness:c, on_topic:o, delivery:d, reason:r});
const v = {
  W01: g(2,2,2,"Correct image-versus-container distinction with registry storage and running-process detail; natural spoken length."),
  W02: g(2,2,2,"Accurately explains layer caching and ordering dependency installs before source copy; concise and speakable."),
  W03: g(2,2,2,"Correct latency-versus-archival trade-off with a concrete compliance-retention justification; clean delivery."),
  W04: g(2,2,2,"Correctly names a managed HTTPS endpoint hosting model artifacts plus inference code; well scoped."),
  W05: g(2,2,2,"Accurate DAG definition and clear rationale for acyclic dependency ordering and retries."),
  W06: g(2,2,2,"Correctly ties artifact versioning to reproducibility, lineage, and debugging production failures."),
  W07: g(2,2,2,"Accurate pod-versus-deployment distinction covering replicas, rolling updates, and self-healing."),
  W08: g(2,2,2,"Cleanly separates input distribution shift from a changed input-target relationship; textbook correct."),
  W09: g(2,2,2,"Correctly names environment drift, manual error, reproducibility, and rollback; well structured."),
  W10: g(2,2,2,"Sensible dataset and version prefix layout with immutable snapshots and lifecycle cleanup."),
  W11: g(2,2,2,"Correct builder-versus-runtime split, venv copy, and size plus attack-surface rationale."),
  W12: g(2,2,2,"Correctly frames a sensor as a waiting operator gating the workflow on an external condition."),
  M01: g(2,2,2,"Names PSI and KS tests against a training baseline with thresholded alerting; specific and correct."),
  M02: g(2,2,2,"Correct Pipelines structure with EventBridge scheduling and conditional Model Registry registration."),
  M03: g(2,2,2,"Correct HPA on custom metrics via Prometheus Adapter plus Cluster Autoscaler for node capacity."),
  M04: g(2,2,2,"Correctly cites snowflake infrastructure, environment parity, and fast redeploy; tight and spoken."),
  M05: g(2,2,2,"Correct KMS customer-managed keys, least-privilege IAM, Block Public Access, and TLS in transit."),
  M06: g(2,2,2,"Correctly extends CI past unit tests to schema checks, pipeline integration, and performance regressions."),
  M07: g(2,2,2,"Correct exponential-backoff retries plus a sensor confirming upstream availability before running."),
  M08: g(1,2,2,"Multi-stage, layer consolidation, and dependency audit are right, but Alpine is a poor base for Python ML images."),
  M09: g(2,2,2,"Correct latency-versus-throughput trade-off with apt real-time and offline examples."),
  M10: g(2,2,2,"Good mix of click-through, conversion, MRR, and coverage; omits serving health but answers directly."),
  M11: g(2,2,2,"Correct namespace quotas, priority classes, bin-packing scheduler, and utilization monitoring."),
  M12: g(2,2,2,"Textbook canary with traffic splitting, metric monitoring, and gradual promotion."),
  M13: g(2,2,2,"Correct: secrets manager storage, reference by ARN, value resolved at runtime not committed."),
  M14: g(0,2,1,"Misdescribes S3 Select as byte-range loading and leads with it; misses sharding and FastFile or Pipe modes; phrasing stutters."),
  M15: g(2,2,2,"Correct pattern: stage the payload in object storage and pass only the URI through XCom."),
  M16: g(2,2,2,"Correct registry role: versioning, lineage tracking, and approval gates before promotion."),
  M17: g(2,2,2,"Correct proxy monitoring via prediction and feature distributions while labels are still pending."),
  M18: g(2,2,2,"Correct: NVIDIA Container Toolkit bridges the host driver and the image matches the framework CUDA version."),
  M19: g(2,2,2,"Correct liveness and readiness split with readiness gated on model weights being loaded."),
  M20: g(2,2,2,"Strong contract framing: schema validation, statistical profiling, and tests on a versioned snapshot."),
  M21: g(2,2,2,"Correct: one template with per-environment config, account isolation, and one promoted artifact."),
  M22: g(2,2,2,"Correct Bayesian search with trial pruning and early stopping to cut wasted compute."),
  M23: g(1,2,2,"Circular and vague; never names a concrete trigger such as sustained metric loss, drift persistence, or label volume."),
  M24: g(2,2,2,"Correct chunked sequential backfill that respects concurrency limits and database load."),
  M25: g(1,2,2,"Plausible but generic; never addresses versioned S3 objects, backups, or derived copies already trained on."),
  M26: g(2,2,2,"Correct centralized hardened base image with automated rebuilds, scanning, and cascading redeploys."),
  M27: g(2,2,2,"Balanced both sides: mTLS and traffic splitting for, sidecar overhead and latency against."),
  M28: g(2,2,2,"Correct feature store answer that explicitly names training-serving skew as the failure prevented."),
  H01: g(2,2,2,"Sound triage order: distribution comparison, then upstream pipeline changes, then silent serving failures."),
  H02: g(2,2,2,"Excellent SageMaker specificity: ModelLatency versus OverheadLatency, utilization, payload size, queuing."),
  H03: g(2,2,1,"Correct design and guardrails, but at about 101 words it is too long to deliver naturally."),
  H04: g(2,2,2,"Correct: kubelet and node pressure metrics, OOMKill events, and requests-versus-limits comparison."),
  H05: g(2,2,2,"Sensible triage of task durations, data volume, contention, and worker concurrency limits."),
  H06: g(1,2,2,"Prefix-partition diagnosis is right, but S3 Transfer Acceleration does not relieve in-region read throttling."),
  H07: g(2,2,2,"Gives a real discriminator: localized shift means drift, systemic quality drop means broken pipeline."),
  H08: g(2,2,2,"Sharp and specific: digest comparison, injected env and mounts, then CPU architecture mismatch."),
  H09: g(2,2,2,"Correct drift detection then reconciling the template or importing the resource back under management."),
  H10: g(2,2,2,"Covers both halves: immediate version rollback and timestamped isolation of corrupted downstream records."),
  H11: g(2,2,2,"Reasonable before-and-after profiling comparison, though it never mentions reading the actual code diff."),
  H12: g(1,2,2,"Active-active with a global load balancer is right, but asynchronous replication does not ensure consistency.")
};
fs.writeFileSync(out, JSON.stringify(v, null, 2), 'utf8');
console.log('written keys:', Object.keys(v).length);
