@echo off
rem DRY RUN twin of launch-eq.cmd, task Natively-flight-eq-dry: the same preconditions, environment block, commit check, committed-text shas, wav:check, dist proofs and behavioural guard, then it stops. No flight, no app, no audio, no API call.
rem Generated by gen-launchers-eq.mjs from launch-eq-src.txt. The flight launcher and this one are composed from the same common section, so they cannot drift apart. Never edit this file by hand and never with sed.
rem Its GUARD OK line and its NIGHT GATES OK line are required before the real task is registered. The precheck task starts this task itself and reads its log.
rem Same placeholder rule as the flight launcher: node gen-launchers-eq.mjs --commit followed by the registered HEAD hash and --t followed by the task time.
rem Exit codes are the flight launcher's steps before the flight: 9, 8, 7, 6, 12, 14, 5, 3, 4, and 0 when every check passed. This guard line does not pass --require-precheck: no precheck exists yet when the dry twin runs.
rem NOTE ON STYLE: no parentheses inside any echo in an if-block, see launch-eq.cmd.
if not exist "electron\test\golden\interview60.flight.mjs" (
  echo wrong working directory: %CD% >> "%TEMP%\natively-eq-launcher-error.log"
  exit /b 9
)
if not exist "electron\test\golden\scenario50.wav" (
  echo scenario50.wav missing - build the audio first >> "%TEMP%\natively-eq-launcher-error.log"
  exit /b 8
)
if not exist "electron\test\golden\scenario50.questions.mjs" (
  echo scenario50 roster missing from this checkout >> "%TEMP%\natively-eq-launcher-error.log"
  exit /b 7
)
rem Guard: the harness must stop the app when a run ends - 5952b23.
findstr /C:"process.on('exit', appStop)" "electron\test\golden\interview60.run.mjs" >nul 2>&1
if not "%errorlevel%"=="0" (
  echo the harness does not stop the app when a run ends - pick 5952b23 into this checkout >> "%TEMP%\natively-eq-launcher-error.log"
  exit /b 6
)
rem The environment of section 2: every variable that changes a model, a level, the hedge or the follow-up parent is cleared. A set with no value UNSETS the name in cmd. NATIVELY_VERBAL_HEDGE is cleared too: the hedge is ON by default and the guard refuses any value of it. The three names after the roster are this hour's own: the flag under test, the focused arms off, and the task time.
set NATIVELY_STT_PROVIDER=deepgram
set NATIVELY_ROSTER=scenario50
set NATIVELY_SCENARIOS=S1,S2
set NATIVELY_EARLIER_QUESTION=1
set NATIVELY_FLIGHT_FOCUSED=off
set NATIVELY_EQ_T=2026-10-05 21:00
set NATIVELY_GEMINI_THINKING_LEVEL=
set NATIVELY_VERBAL_PRIMARY_MODEL=
set NATIVELY_VERBAL_HEDGE=
set NATIVELY_VERBAL_HEDGE_TRIGGER_MS=
set NATIVELY_FOLLOWUP_PARENT=
set NATIVELY_LIVE_MODEL=
set NATIVELY_LIVE_MODE=
set NATIVELY_AUTOSTART_MEETING=
set NATIVELY_CAPTURE_PROMPTS=
set NATIVELY_QUESTION_DETECTION_MODEL=
set NATIVELY_FIRST_TOKEN_TIMEOUT_MS=
set NATIVELY_TURN_GATE_MS=
set NATIVELY_TURN_SETTLE_MS=
set NATIVELY_TURN_UNFINISHED_HOLD_MS=
set NATIVELY_TURN_CONTINUATION_MS=
set NATIVELY_TURN_MAX_HOLD_MS=
set NATIVELY_TURN_WORDLESS_GRACE_MS=
set NATIVELY_DETECTOR_CALIBRATE=
set NATIVELY_DETECTOR_CHAIN_TEST=
set NATIVELY_DETECTOR_CHAIN_TEST_QUESTIONS=
set NATIVELY_GEMMA_TTFT_MS=
set NATIVELY_GEMMA_MAX_ATTEMPTS=
set NATIVELY_GEMMA_VISION_TTFT_MS=
set NATIVELY_GEMMA_VISION_TTFT_BASE_MS=
set NATIVELY_GEMMA_VISION_TTFT_PER_IMAGE_MS=
set NATIVELY_GEMMA_VISION_MAX_ATTEMPTS=
set NATIVELY_API_URL=
set NATIVELY_BUILD_ALL_MAC_ARCHES=
set I60_PROBE_DEADLINE_MIN=
set NATIVELY_FLIGHT_COMMIT=56bda9eb64b65a190c73788b5f86a550f6809f6a
rem The commit check: 40 lowercase hex characters, nothing else. An unfilled placeholder, a short hash, a long one and an uppercase one all fail here, before anything runs. findstr cannot count to 40 in a pattern, so the length is tested by substring.
set COMMIT_OK=1
echo %NATIVELY_FLIGHT_COMMIT%| findstr /R /X "[0-9a-f][0-9a-f]*" >nul 2>&1
if errorlevel 1 set COMMIT_OK=0
if "%NATIVELY_FLIGHT_COMMIT:~39,1%"=="" set COMMIT_OK=0
if not "%NATIVELY_FLIGHT_COMMIT:~40,1%"=="" set COMMIT_OK=0
if "%COMMIT_OK%"=="0" (
  echo NATIVELY_FLIGHT_COMMIT is not a full 40 character hash - the placeholder was not filled in - run gen-launchers-eq.mjs with the commit >> "%TEMP%\natively-eq-launcher-error.log"
  exit /b 12
)
echo === LAUNCHER eq-dry start %DATE% %TIME% commit %NATIVELY_FLIGHT_COMMIT% T %NATIVELY_EQ_T% === >> electron\test\golden\interview60.runs\flight-eq-dry.launcher.log
rem The committed texts, FIRST: the sha256 of each passes file as committed at HEAD, then the arming record's sha256 or ARMING absent. The dry run precedes the record, so absent is not an error here; the precheck gates on the record, and the result note quotes these lines.
"C:\Program Files\nodejs\node.exe" "%~dp0eq-sha-lines.mjs" --root "%CD%" --passes "2026-10-04-turn-followup-result.md,PREREGISTER-h40d.md" --arming "%~dp0ARMING-flight-eq.md" >> electron\test\golden\interview60.runs\flight-eq-dry.launcher.log 2>&1
if not "%errorlevel%"=="0" (
  echo a committed text is missing at HEAD - see flight-eq-dry.launcher.log >> "%TEMP%\natively-eq-launcher-error.log"
  exit /b 14
)
rem Guard: the audio must hold exactly the roster's clips and gaps.
"C:\Program Files\nodejs\node.exe" electron\test\golden\interview60.run.mjs wav:check >> electron\test\golden\interview60.runs\flight-eq-dry.launcher.log 2>&1
if not "%errorlevel%"=="0" (
  echo scenario50.wav does not match the scenario50 roster - see flight-eq-dry.launcher.log >> "%TEMP%\natively-eq-launcher-error.log"
  exit /b 5
)
rem Dist proofs 1: the cue build markers, the four earlier-question markers with the sha256 of earlierQuestion.js, and parity-dist against MAIN's dist, all printed into the log. The root is passed as the current folder in full: dist-proof.mjs fails on a relative root such as a single dot.
echo === DIST BEFORE THE RUN === >> electron\test\golden\interview60.runs\flight-eq-dry.launcher.log
"C:\Program Files\nodejs\node.exe" "%~dp0eq-proofs.mjs" --root "%CD%" >> electron\test\golden\interview60.runs\flight-eq-dry.launcher.log 2>&1
if not "%errorlevel%"=="0" (
  echo dist proofs 1 failed - see flight-eq-dry.launcher.log >> "%TEMP%\natively-eq-launcher-error.log"
  exit /b 3
)
rem BEHAVIOURAL guard, the dry form: every check of the real launcher except the precheck stamp, which does not exist when the dry twin runs. Calibrated by breaking each premise once, see guard-eq-cal.txt.
"C:\Program Files\nodejs\node.exe" "%~dp0guard-eq.mjs" >> electron\test\golden\interview60.runs\flight-eq-dry.launcher.log 2>&1
if not "%errorlevel%"=="0" (
  echo behavioural guard failed - see flight-eq-dry.launcher.log >> "%TEMP%\natively-eq-launcher-error.log"
  exit /b 4
)
echo === LAUNCHER eq-dry done %DATE% %TIME% === >> electron\test\golden\interview60.runs\flight-eq-dry.launcher.log
exit /b 0
