@echo off
rem DRY RUN twin of launch-h40d.cmd, task Natively-flight-h40d-dry: the same preconditions, environment block, commit check, wav:check, dist proof and behavioural guard, then it stops. No flight, no app, no audio, no API call.
rem Generated by gen-launchers.mjs from launch-h40d-src.txt. The flight launcher and this one are composed from the same common section, so they cannot drift apart. Never edit this file by hand and never with sed.
rem Its GUARD OK line and its DIST PROOF verdict line are required before the real task is registered, r4 section 7.4.
rem Same placeholder rule as the flight launcher: node gen-launchers.mjs --commit followed by the registered HEAD hash.
rem Exit codes are the flight launcher's steps before the flight: 9, 8, 7, 6, 12, 5, 3, 4, and 0 when every check passed.
rem NOTE ON STYLE: no parentheses inside any echo in an if-block, see launch-h40d.cmd.
if not exist "electron\test\golden\interview60.flight.mjs" (
  echo wrong working directory: %CD% >> "%TEMP%\natively-h40d-launcher-error.log"
  exit /b 9
)
if not exist "electron\test\golden\holdout40.wav" (
  echo holdout40.wav missing - build the audio first >> "%TEMP%\natively-h40d-launcher-error.log"
  exit /b 8
)
if not exist "electron\test\golden\holdout40.questions.mjs" (
  echo holdout40 roster missing from this checkout - merge it first >> "%TEMP%\natively-h40d-launcher-error.log"
  exit /b 7
)
rem Guard: the harness must stop the app when a run ends - 5952b23.
findstr /C:"process.on('exit', appStop)" "electron\test\golden\interview60.run.mjs" >nul 2>&1
if errorlevel 1 (
  echo the harness does not stop the app when a run ends - pick 5952b23 into this checkout >> "%TEMP%\natively-h40d-launcher-error.log"
  exit /b 6
)
rem The environment of r4 section 2: every variable that changes a model, a level, the hedge or the follow-up parent is cleared. A set with no value UNSETS the name in cmd. NATIVELY_VERBAL_HEDGE is cleared too: the hedge is ON by default and the guard refuses any value of it.
set NATIVELY_STT_PROVIDER=deepgram
set NATIVELY_ROSTER=holdout40
set NATIVELY_SCENARIOS=
set NATIVELY_GEMINI_THINKING_LEVEL=
set NATIVELY_VERBAL_PRIMARY_MODEL=
set NATIVELY_VERBAL_HEDGE=
set NATIVELY_VERBAL_HEDGE_TRIGGER_MS=
set NATIVELY_FOLLOWUP_PARENT=
set NATIVELY_LIVE_MODEL=
set NATIVELY_LIVE_MODE=
set NATIVELY_AUTOSTART_MEETING=
set NATIVELY_CAPTURE_PROMPTS=
set NATIVELY_QUESTION_DETECTION_MODEL=
set NATIVELY_FIRST_TOKEN_TIMEOUT_MS=
set NATIVELY_TURN_GATE_MS=
set NATIVELY_TURN_SETTLE_MS=
set NATIVELY_TURN_UNFINISHED_HOLD_MS=
set NATIVELY_TURN_CONTINUATION_MS=
set NATIVELY_TURN_MAX_HOLD_MS=
set NATIVELY_TURN_WORDLESS_GRACE_MS=
set NATIVELY_DETECTOR_CALIBRATE=
set NATIVELY_DETECTOR_CHAIN_TEST=
set NATIVELY_DETECTOR_CHAIN_TEST_QUESTIONS=
set NATIVELY_GEMMA_TTFT_MS=
set NATIVELY_GEMMA_MAX_ATTEMPTS=
set NATIVELY_GEMMA_VISION_TTFT_MS=
set NATIVELY_GEMMA_VISION_TTFT_BASE_MS=
set NATIVELY_GEMMA_VISION_TTFT_PER_IMAGE_MS=
set NATIVELY_GEMMA_VISION_MAX_ATTEMPTS=
set NATIVELY_API_URL=
set NATIVELY_BUILD_ALL_MAC_ARCHES=
set I60_PROBE_DEADLINE_MIN=
set NATIVELY_FLIGHT_COMMIT=@@REGISTERED_HEAD_FULL_HASH@@
rem The commit check: 40 lowercase hex characters, nothing else. An unfilled placeholder, a short hash, a long one and an uppercase one all fail here, before anything runs. findstr cannot count to 40 in a pattern, so the length is tested by substring.
set COMMIT_OK=1
echo %NATIVELY_FLIGHT_COMMIT%| findstr /R /X "[0-9a-f][0-9a-f]*" >nul 2>&1
if errorlevel 1 set COMMIT_OK=0
if "%NATIVELY_FLIGHT_COMMIT:~39,1%"=="" set COMMIT_OK=0
if not "%NATIVELY_FLIGHT_COMMIT:~40,1%"=="" set COMMIT_OK=0
if "%COMMIT_OK%"=="0" (
  echo NATIVELY_FLIGHT_COMMIT is not a full 40 character hash - the placeholder was not filled in - run gen-launchers.mjs with the commit >> "%TEMP%\natively-h40d-launcher-error.log"
  exit /b 12
)
echo === LAUNCHER h40d-dry start %DATE% %TIME% commit %NATIVELY_FLIGHT_COMMIT% === >> electron\test\golden\interview60.runs\flight-h40d-dry.launcher.log
rem Guard: the audio must hold exactly the roster's clips and gaps.
"C:\Program Files\nodejs\node.exe" electron\test\golden\interview60.run.mjs wav:check >> electron\test\golden\interview60.runs\flight-h40d-dry.launcher.log 2>&1
if errorlevel 1 (
  echo holdout40.wav does not match the holdout40 roster - see flight-h40d-dry.launcher.log >> "%TEMP%\natively-h40d-launcher-error.log"
  exit /b 55
)
rem Dist proof 1: the dist in MAIN is the combined cue build, every marker as expected. The root is passed as the current folder in full: dist-proof.mjs fails on a relative root such as a single dot.
echo === DIST BEFORE THE RUN === >> electron\test\golden\interview60.runs\flight-h40d-dry.launcher.log
"C:\Program Files\nodejs\node.exe" "C:\Users\sotka\OneDrive\Masaüstü\natively-lab\sp\dist-proof.mjs" --root "%CD%" --expect combined --prefix-count 3 --offers-marker "offers block before the spoken answer" >> electron\test\golden\interview60.runs\flight-h40d-dry.launcher.log 2>&1
if errorlevel 1 (
  echo dist proof 1 failed - the dist is not the combined build - see flight-h40d-dry.launcher.log >> "%TEMP%\natively-h40d-launcher-error.log"
  exit /b 3
)
rem BEHAVIOURAL guard: roster, no model or thinking override, the built default and fallback and their levels, the R09 fix, the hedge resolving ON with its variable unset, trigger 5000 ms, follow-up parent off, dist not stale, the HEAD pin and the .env name scan, the cue build markers and knowledge mode ON. Calibrated by breaking each premise once, see guard-h40d-cal.txt.
"C:\Program Files\nodejs\node.exe" "%~dp0guard-h40d.mjs" >> electron\test\golden\interview60.runs\flight-h40d-dry.launcher.log 2>&1
if errorlevel 1 (
  echo behavioural guard failed - see flight-h40d-dry.launcher.log >> "%TEMP%\natively-h40d-launcher-error.log"
  exit /b 4
)
echo === LAUNCHER h40d-dry done %DATE% %TIME% === >> electron\test\golden\interview60.runs\flight-h40d-dry.launcher.log
exit /b 0
