@echo off
rem PRE-HOUR MAIN START, task Natively-prestart-h40d, r4 section 7.3: the one seam the cue re-smoke does not cross, MAIN's own checkout, .env loader, rebuilt dist and single-instance lock with cue mode in it.
rem Runs the dry twin's chain, then interview60.run.mjs app:start, then probe, then a 60 second wait, then app:stop, all appending to the log. app:stop runs whatever happened after app:start. Run it from a scheduled task only, never from a Claude session, which reads a shadow credentials store.
rem NATIVELY_FLIGHT_COMMIT here is NOT the registered HEAD: the registered HEAD is the pre-registration commit and does not exist yet when this runs. It must be MAIN's HEAD at prestart time: node gen-launchers.mjs --prestart-commit followed by that hash.
rem Generated by gen-launchers.mjs from launch-h40d-src.txt. Never edit this file by hand and never with sed.
rem Before it fires: no Natively window may be open in MAIN, because app:stop kills every electron.exe of this checkout, and the speaker must be on, because probe plays a 34 second continuous clip aloud.
rem Exit codes: the dry twin's 9, 8, 7, 6, 12, 5, 3, 4, then 10 app:start failed, 11 probe not ready, 13 app:stop failed, 3 again for a dist proof failure after the run, 0 when everything passed. Precedence after the run: 3, 10, 11, 13.
rem Afterwards the controller copies natively_debug.log from MAIN into the prestart folder of the validation hour, right after app:stop and before any other app start rotates it. The dir line below fingerprints the file as app:stop left it.
rem NOTE ON STYLE: no parentheses inside any echo in an if-block, see launch-h40d.cmd.
if not exist "electron\test\golden\interview60.flight.mjs" (
  echo wrong working directory: %CD% >> "%TEMP%\natively-h40d-launcher-error.log"
  exit /b 9
)
if not exist "electron\test\golden\holdout40.wav" (
  echo holdout40.wav missing - build the audio first >> "%TEMP%\natively-h40d-launcher-error.log"
  exit /b 8
)
if not exist "electron\test\golden\holdout40.questions.mjs" (
  echo holdout40 roster missing from this checkout - merge it first >> "%TEMP%\natively-h40d-launcher-error.log"
  exit /b 7
)
rem Guard: the harness must stop the app when a run ends - 5952b23.
findstr /C:"process.on('exit', appStop)" "electron\test\golden\interview60.run.mjs" >nul 2>&1
if errorlevel 1 (
  echo the harness does not stop the app when a run ends - pick 5952b23 into this checkout >> "%TEMP%\natively-h40d-launcher-error.log"
  exit /b 6
)
rem The environment of r4 section 2: every variable that changes a model, a level, the hedge or the follow-up parent is cleared. A set with no value UNSETS the name in cmd. NATIVELY_VERBAL_HEDGE is cleared too: the hedge is ON by default and the guard refuses any value of it.
set NATIVELY_STT_PROVIDER=deepgram
set NATIVELY_ROSTER=holdout40
set NATIVELY_SCENARIOS=
set NATIVELY_GEMINI_THINKING_LEVEL=
set NATIVELY_VERBAL_PRIMARY_MODEL=
set NATIVELY_VERBAL_HEDGE=
set NATIVELY_VERBAL_HEDGE_TRIGGER_MS=
set NATIVELY_FOLLOWUP_PARENT=
set NATIVELY_LIVE_MODEL=
set NATIVELY_LIVE_MODE=
set NATIVELY_AUTOSTART_MEETING=
set NATIVELY_CAPTURE_PROMPTS=
set NATIVELY_QUESTION_DETECTION_MODEL=
set NATIVELY_FIRST_TOKEN_TIMEOUT_MS=
set NATIVELY_TURN_GATE_MS=
set NATIVELY_TURN_SETTLE_MS=
set NATIVELY_TURN_UNFINISHED_HOLD_MS=
set NATIVELY_TURN_CONTINUATION_MS=
set NATIVELY_TURN_MAX_HOLD_MS=
set NATIVELY_TURN_WORDLESS_GRACE_MS=
set NATIVELY_DETECTOR_CALIBRATE=
set NATIVELY_DETECTOR_CHAIN_TEST=
set NATIVELY_DETECTOR_CHAIN_TEST_QUESTIONS=
set NATIVELY_GEMMA_TTFT_MS=
set NATIVELY_GEMMA_MAX_ATTEMPTS=
set NATIVELY_GEMMA_VISION_TTFT_MS=
set NATIVELY_GEMMA_VISION_TTFT_BASE_MS=
set NATIVELY_GEMMA_VISION_TTFT_PER_IMAGE_MS=
set NATIVELY_GEMMA_VISION_MAX_ATTEMPTS=
set NATIVELY_API_URL=
set NATIVELY_BUILD_ALL_MAC_ARCHES=
set I60_PROBE_DEADLINE_MIN=
set NATIVELY_FLIGHT_COMMIT=fedcba9876543210fedcba9876543210fedcba98
rem The commit check: 40 lowercase hex characters, nothing else. An unfilled placeholder, a short hash, a long one and an uppercase one all fail here, before anything runs. findstr cannot count to 40 in a pattern, so the length is tested by substring.
set COMMIT_OK=1
echo %NATIVELY_FLIGHT_COMMIT%| findstr /R /X "[0-9a-f][0-9a-f]*" >nul 2>&1
if errorlevel 1 set COMMIT_OK=0
if "%NATIVELY_FLIGHT_COMMIT:~39,1%"=="" set COMMIT_OK=0
if not "%NATIVELY_FLIGHT_COMMIT:~40,1%"=="" set COMMIT_OK=0
if "%COMMIT_OK%"=="0" (
  echo NATIVELY_FLIGHT_COMMIT is not a full 40 character hash - the placeholder was not filled in - run gen-launchers.mjs with the commit >> "%TEMP%\natively-h40d-launcher-error.log"
  exit /b 12
)
echo === LAUNCHER h40d-prestart start %DATE% %TIME% commit %NATIVELY_FLIGHT_COMMIT% === >> electron\test\golden\interview60.runs\flight-h40d-prestart.launcher.log
rem Guard: the audio must hold exactly the roster's clips and gaps.
"C:\Program Files\nodejs\node.exe" C:\Users\sotka\AppData\Local\Temp\claude\C-407A~1\9C5886~1\SCRATC~1\VALIDA~1\INSTRU~1\LAUNCH~1\cal\b16\stub\stub-run.mjs wav:check >> electron\test\golden\interview60.runs\flight-h40d-prestart.launcher.log 2>&1
if errorlevel 1 (
  echo holdout40.wav does not match the holdout40 roster - see flight-h40d-prestart.launcher.log >> "%TEMP%\natively-h40d-launcher-error.log"
  exit /b 5
)
rem Dist proof 1: the dist in MAIN is the combined cue build, every marker as expected. The root is passed as the current folder in full: dist-proof.mjs fails on a relative root such as a single dot.
echo === DIST BEFORE THE RUN === >> electron\test\golden\interview60.runs\flight-h40d-prestart.launcher.log
"C:\Program Files\nodejs\node.exe" "C:\Users\sotka\OneDrive\Masaüstü\natively-lab\sp\dist-proof.mjs" --root "%CD%" --expect combined --prefix-count 3 --offers-marker "offers block before the spoken answer" >> electron\test\golden\interview60.runs\flight-h40d-prestart.launcher.log 2>&1
if errorlevel 1 (
  echo dist proof 1 failed - the dist is not the combined build - see flight-h40d-prestart.launcher.log >> "%TEMP%\natively-h40d-launcher-error.log"
  exit /b 3
)
rem BEHAVIOURAL guard: roster, no model or thinking override, the built default and fallback and their levels, the R09 fix, the hedge resolving ON with its variable unset, trigger 5000 ms, follow-up parent off, dist not stale, the HEAD pin and the .env name scan, the cue build markers and knowledge mode ON. Calibrated by breaking each premise once, see guard-h40d-cal.txt.
"C:\Program Files\nodejs\node.exe" "%~dp0guard-h40d.mjs" >> electron\test\golden\interview60.runs\flight-h40d-prestart.launcher.log 2>&1
if errorlevel 1 (
  echo behavioural guard failed - see flight-h40d-prestart.launcher.log >> "%TEMP%\natively-h40d-launcher-error.log"
  exit /b 4
)
rem app:start returns once the app is listening in Auto, or exits 1 after two attempts. Whatever it did, app:stop runs below.
set START_EXIT=0
set PROBE_EXIT=0
echo === PRESTART app:start %DATE% %TIME% === >> electron\test\golden\interview60.runs\flight-h40d-prestart.launcher.log
"C:\Program Files\nodejs\node.exe" C:\Users\sotka\AppData\Local\Temp\claude\C-407A~1\9C5886~1\SCRATC~1\VALIDA~1\INSTRU~1\LAUNCH~1\cal\b16\stub\stub-run.mjs app:start >> electron\test\golden\interview60.runs\flight-h40d-prestart.launcher.log 2>&1
set START_EXIT=%errorlevel%
echo === app:start exit %START_EXIT% === >> electron\test\golden\interview60.runs\flight-h40d-prestart.launcher.log
if not "%START_EXIT%"=="0" goto stop
rem probe pings 3.1 lite five times, runs the preflight and plays the continuous probe, requiring the app's own log to show it heard a question. It does not wait for the answers.
"C:\Program Files\nodejs\node.exe" C:\Users\sotka\AppData\Local\Temp\claude\C-407A~1\9C5886~1\SCRATC~1\VALIDA~1\INSTRU~1\LAUNCH~1\cal\b16\stub\stub-run.mjs probe >> electron\test\golden\interview60.runs\flight-h40d-prestart.launcher.log 2>&1
set PROBE_EXIT=%errorlevel%
echo === probe exit %PROBE_EXIT% === >> electron\test\golden\interview60.runs\flight-h40d-prestart.launcher.log
rem The wait lets the last answer finish, or a cues line with no full line reads NOT CLEAN in check-smoke-cues. ping cannot refuse: timeout exits at once when its input is redirected. Unconditional after a start, with its two timestamps in the log.
echo === WAIT 60 s begins %TIME% === >> electron\test\golden\interview60.runs\flight-h40d-prestart.launcher.log
ping -n 61 127.0.0.1 >nul
echo === WAIT 60 s ends %TIME% === >> electron\test\golden\interview60.runs\flight-h40d-prestart.launcher.log
:stop
echo === PRESTART app:stop %DATE% %TIME% === >> electron\test\golden\interview60.runs\flight-h40d-prestart.launcher.log
"C:\Program Files\nodejs\node.exe" C:\Users\sotka\AppData\Local\Temp\claude\C-407A~1\9C5886~1\SCRATC~1\VALIDA~1\INSTRU~1\LAUNCH~1\cal\b16\stub\stub-run.mjs app:stop >> electron\test\golden\interview60.runs\flight-h40d-prestart.launcher.log 2>&1
set STOP_EXIT=%errorlevel%
echo === app:stop exit %STOP_EXIT% === >> electron\test\golden\interview60.runs\flight-h40d-prestart.launcher.log
echo === natively_debug.log as app:stop left it === >> electron\test\golden\interview60.runs\flight-h40d-prestart.launcher.log
dir natively_debug.log >> electron\test\golden\interview60.runs\flight-h40d-prestart.launcher.log 2>&1
rem Every failure is named in the error log before the first exit, so one run shows all of them. Exit code precedence: 3, then 10, then 11, then 13.
if not "%START_EXIT%"=="0" echo app:start failed - see flight-h40d-prestart.launcher.log >> "%TEMP%\natively-h40d-launcher-error.log"
if not "%PROBE_EXIT%"=="0" echo probe not ready - see flight-h40d-prestart.launcher.log >> "%TEMP%\natively-h40d-launcher-error.log"
if not "%STOP_EXIT%"=="0" echo app:stop failed - an app may still be running - see flight-h40d-prestart.launcher.log >> "%TEMP%\natively-h40d-launcher-error.log"
rem Dist proof after the run: nothing the app did may have changed the dist.
echo === DIST AFTER THE RUN === >> electron\test\golden\interview60.runs\flight-h40d-prestart.launcher.log
"C:\Program Files\nodejs\node.exe" "C:\Users\sotka\OneDrive\Masaüstü\natively-lab\sp\dist-proof.mjs" --root "%CD%" --expect combined --prefix-count 3 --offers-marker "offers block before the spoken answer" >> electron\test\golden\interview60.runs\flight-h40d-prestart.launcher.log 2>&1
if errorlevel 1 (
  echo dist proof 2 failed - the dist after the prestart is not the combined build - see flight-h40d-prestart.launcher.log >> "%TEMP%\natively-h40d-launcher-error.log"
  exit /b 3
)
if not "%START_EXIT%"=="0" exit /b 10
if not "%PROBE_EXIT%"=="0" exit /b 11
if not "%STOP_EXIT%"=="0" exit /b 13
echo === LAUNCHER h40d-prestart done %DATE% %TIME% === >> electron\test\golden\interview60.runs\flight-h40d-prestart.launcher.log
exit /b 0
