/**
 * Generates live40.questions.mjs from natively-lab\sp\live40\items.json.
 *
 *   node electron/test/golden/live40.gen.mjs [--items <items.json>]
 *
 * Refuses (exit 2) any items.json whose sha256 is not the one the router-default spec
 * pins: the roster is a stimulus, and a silently different one would make every
 * live40 hour incomparable with the others.
 *
 * Output order is items.json's, which is the chain order (31 chains, SET-draft section 5).
 * A parent that does not precede its child in the same chain, or an item list that
 * differs from the chains' own order, refuses with exit 1 rather than writing a roster
 * the harness would play in the wrong order.
 */
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ITEMS_SHA256 = 'e531772bdc6e9c23865156286d8441c51521c62be74413bc56322090c81b2aaf';
const DEFAULT_ITEMS = 'C:\\Users\\sotka\\OneDrive\\Masaüstü\\natively-lab\\sp\\live40\\items.json';
// 20 s on every item: spec 7.4's derivation (worst close 16 s + 2 s pairing window + 2 s margin).
const GAP_MS = 20000;

const args = process.argv.slice(2);
const flag = (name) => { const i = args.indexOf(name); return i >= 0 ? args[i + 1] : undefined; };
const itemsPath = flag('--items') ?? DEFAULT_ITEMS;
const outPath = path.join(HERE, 'live40.questions.mjs');

const raw = fs.readFileSync(itemsPath);
const sha = crypto.createHash('sha256').update(raw).digest('hex');
if (sha !== ITEMS_SHA256) {
    console.error(`items.json sha256 ${sha} refused (expected ${ITEMS_SHA256})`);
    process.exit(2);
}

const src = JSON.parse(raw.toString('utf8'));
const chainOrder = src.chains.flatMap((c) => c.items);
const ids = src.items.map((x) => x.id);
const problems = [];
if (src.items.length !== 47) problems.push(`expected 47 items, found ${src.items.length}`);
if (JSON.stringify(ids) !== JSON.stringify(chainOrder)) problems.push('items are not in the chains\' order');
const pos = new Map(ids.map((id, i) => [id, i]));
for (const x of src.items) {
    if (x.parent == null) continue;
    const p = src.items[pos.get(x.parent)];
    if (!p || pos.get(x.parent) >= pos.get(x.id)) problems.push(`${x.id}: parent ${x.parent} does not precede it`);
    else if (p.chain !== x.chain) problems.push(`${x.id}: parent ${x.parent} is in another chain`);
}
if (problems.length) {
    console.error(`live40 items refused:\n  ${problems.join('\n  ')}`);
    process.exit(1);
}

const items = src.items.map((x) => ({
    id: x.id,
    q: x.text,
    gapMs: GAP_MS,
    chain: x.chain,
    ...(x.parent ? { parent: x.parent } : {}),
    route: x.route,
    class: x.class,
    // run.mjs computeOffsets copies level and topic into the timeline.
    level: x.route,
    topic: x.chain,
}));

const out = `/**
 * GENERATED by live40.gen.mjs from natively-lab\\sp\\live40\\items.json
 * (sha256 ${ITEMS_SHA256}). Do not edit: re-run the generator.
 *
 * 47 items in chain order (31 chains). \`chain\` is the chain id (C01...), \`parent\` the item it
 * follows up, \`route\` the router40 key (EASY | HARD), \`class\` E | H | QF | AF.
 * \`level\` and \`topic\` mirror route and chain for the harness timeline. Every gap is 20 s
 * (spec 7.4); the audio clips are router40's, reused (live40.clips.mjs).
 */
export const LIVE40 = ${JSON.stringify(items, null, 4)};
`;
fs.writeFileSync(outPath, out);
console.log(`wrote ${path.basename(outPath)}  ${items.length} items  source sha256 ${ITEMS_SHA256.slice(0, 12)}`);
